import React, { useEffect, useState } from "react";
import { KeyRound, Plus, Shield, UserCheck, UserX } from "lucide-react";
import type { UserRecord } from "../types/app.js";
import { api } from "../services/api.js";

export const Admin: React.FC = () => {
 const [users,setUsers]=useState<UserRecord[]>([]); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [role,setRole]=useState("viewer"); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
 async function load(){try{setUsers(await api.getUsers());}catch(err){setError(err instanceof Error?err.message:"Unable to load users");}}
 useEffect(()=>{void load();},[]);
 async function create(){setBusy("create");try{const u=await api.createUser({email:email.trim(),password,role});setUsers((x)=>[...x,u].sort((a,b)=>a.email.localeCompare(b.email)));setEmail("");setPassword("");}catch(err){setError(err instanceof Error?err.message:"Unable to create user");}finally{setBusy(null);}}
 async function toggle(user:UserRecord){setBusy(user.id);try{const u=await api.updateUser(user.id,{is_active:!user.is_active});setUsers((x)=>x.map((item)=>item.id===user.id?u:item));}catch(err){setError(err instanceof Error?err.message:"Unable to update user");}finally{setBusy(null);}}
 return <main className="mx-auto max-w-7xl space-y-6 p-5 sm:p-8"><div><div className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Administration</div><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">Access management</h1><p className="mt-2 text-sm text-slate-500">Create operational accounts and control their active state.</p></div>{error&&<div role="alert" className="rounded-xl border border-rose-500/15 bg-rose-500/5 px-4 py-3 text-sm text-rose-300">{error}</div>}
 <div className="rounded-2xl border border-white/7 bg-white/[0.02] p-5"><div className="mb-4 flex items-center gap-2 text-sm font-medium text-white"><Plus className="h-4 w-4 text-cyan-300"/>Create user</div><div className="grid gap-3 md:grid-cols-[1.2fr_1.2fr_0.8fr_auto]"><input value={email} onChange={(e)=>setEmail(e.target.value)} type="email" placeholder="operator@company.com" className="rounded-xl border border-white/8 bg-black/10 px-4 py-3 text-sm text-white"/><input value={password} onChange={(e)=>setPassword(e.target.value)} type="password" placeholder="Minimum 8 characters" className="rounded-xl border border-white/8 bg-black/10 px-4 py-3 text-sm text-white"/><select value={role} onChange={(e)=>setRole(e.target.value)} className="rounded-xl border border-white/8 bg-slate-900 px-4 py-3 text-sm text-white"><option value="viewer">Viewer</option><option value="operator">Operator</option><option value="admin">Admin</option></select><button disabled={busy==="create"||!email||password.length<8} onClick={()=>void create()} className="rounded-xl bg-cyan-300 px-5 py-3 text-sm font-semibold text-slate-950 disabled:opacity-40">{busy==="create"?"Creating…":"Create"}</button></div></div>
 <div className="overflow-hidden rounded-2xl border border-white/7 bg-slate-900/50"><div className="border-b border-white/6 px-5 py-4 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Users</div><div className="divide-y divide-white/6">{users.map((user)=><div key={user.id} className="flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-400/5"><Shield className="h-4 w-4 text-indigo-300"/></div><div><div className="text-sm font-medium text-white">{user.email}</div><div className="mt-1 flex items-center gap-2 text-xs text-slate-600"><KeyRound className="h-3 w-3"/>{user.role}</div></div></div><div className="flex items-center gap-3">{user.is_active?<span className="flex items-center gap-1.5 text-xs text-emerald-300"><UserCheck className="h-3.5 w-3.5"/>Active</span>:<span className="flex items-center gap-1.5 text-xs text-slate-600"><UserX className="h-3.5 w-3.5"/>Inactive</span>}<button disabled={busy===user.id} onClick={()=>void toggle(user)} className="rounded-xl border border-white/8 px-3 py-2 text-xs text-slate-400 disabled:opacity-40">{user.is_active?"Deactivate":"Activate"}</button></div></div>)}</div></div>
 </main>;
};
export default Admin;
