import React, { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BellRing, Check, Filter, RefreshCw } from "lucide-react";
import type { Alert } from "../types/app.js";
import { api } from "../services/api.js";

export const AlertsPage: React.FC = () => {
  const [alerts, setAlerts] = useState<Alert[]>([]); const [activeOnly, setActiveOnly] = useState(false); const [loading, setLoading] = useState(true); const [working, setWorking] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function load() { try { setLoading(true); setError(null); setAlerts((await api.getAlerts(activeOnly)).alerts); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load alerts"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [activeOnly]);
  const active = useMemo(() => alerts.filter((a) => !a.resolved).length, [alerts]); const critical = useMemo(() => alerts.filter((a) => !a.resolved && a.severity === "CRITICAL").length, [alerts]);
  async function acknowledge(id: string) { setWorking(id); try { await api.acknowledgeAlert(id); setAlerts((items) => items.map((a) => a.id === id ? { ...a, acknowledged: true } : a)); } catch (err) { setError(err instanceof Error ? err.message : "Unable to acknowledge alert"); } finally { setWorking(null); } }
  const badge = (severity: Alert["severity"]) => severity === "CRITICAL" ? "border-rose-500/20 bg-rose-500/10 text-rose-300" : severity === "WARNING" ? "border-amber-500/20 bg-amber-500/10 text-amber-300" : "border-sky-500/20 bg-sky-500/10 text-sky-300";
  return <main className="mx-auto max-w-7xl space-y-6 p-5 sm:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Operations</div><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">Alert center</h1><p className="mt-2 text-sm text-slate-500">Persistent anomaly history with acknowledgement workflow.</p></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-white/8 bg-white/[0.03] px-4 py-2.5 text-sm text-slate-300 hover:bg-white/[0.06]"><RefreshCw className="h-4 w-4" />Refresh</button></div>
    <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/7 bg-white/[0.02] p-5"><div className="flex items-center gap-2 text-xs text-slate-500"><BellRing className="h-4 w-4" />Active</div><div className="mt-3 text-3xl font-semibold">{active}</div></div><div className="rounded-2xl border border-white/7 bg-white/[0.02] p-5"><div className="flex items-center gap-2 text-xs text-slate-500"><AlertTriangle className="h-4 w-4" />Critical</div><div className="mt-3 text-3xl font-semibold text-rose-300">{critical}</div></div><label className="flex items-center justify-between rounded-2xl border border-white/7 bg-white/[0.02] p-5 text-sm text-slate-400"><span className="flex items-center gap-2"><Filter className="h-4 w-4" />Active only</span><input type="checkbox" checked={activeOnly} onChange={(e) => setActiveOnly(e.target.checked)} /></label></div>
    {error && <div role="alert" className="rounded-xl border border-rose-500/15 bg-rose-500/5 px-4 py-3 text-sm text-rose-300">{error}</div>}
    <div className="overflow-hidden rounded-2xl border border-white/7 bg-slate-900/50"><div className="border-b border-white/6 px-5 py-4 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Recent alerts</div>{loading ? <div className="p-8 text-sm text-slate-500">Loading…</div> : alerts.length === 0 ? <div className="p-10 text-center text-sm text-slate-500">No alerts match the current filter.</div> : <div className="divide-y divide-white/6">{alerts.map((alert) => <div key={alert.id} className="flex flex-col gap-4 px-5 py-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className={"rounded-full border px-2.5 py-1 text-[10px] font-semibold " + badge(alert.severity)}>{alert.severity}</span><span className="rounded-full border border-white/7 px-2.5 py-1 text-[10px] text-slate-500">{alert.metric}</span>{alert.resolved && <span className="rounded-full border border-emerald-500/20 bg-emerald-500/10 px-2.5 py-1 text-[10px] text-emerald-300">Resolved</span>}{alert.acknowledged && <span className="rounded-full border border-white/7 px-2.5 py-1 text-[10px] text-slate-500">Acknowledged</span>}</div><div className="mt-3 text-sm font-medium text-white">{alert.message}</div><div className="mt-2 text-xs text-slate-600">{new Date(alert.timestamp).toLocaleString()} · value {alert.value.toFixed(2)} · baseline {alert.baseline.toFixed(2)}</div></div>{!alert.resolved && !alert.acknowledged && <button onClick={() => void acknowledge(alert.id)} disabled={working === alert.id} className="inline-flex items-center justify-center gap-2 rounded-xl border border-cyan-400/15 bg-cyan-400/5 px-4 py-2.5 text-xs font-semibold text-cyan-200 disabled:opacity-50"><Check className="h-4 w-4" />{working === alert.id ? "Saving…" : "Acknowledge"}</button>}</div>)}</div>}</div>
  </main>;
};
export default AlertsPage;
