import React, { useEffect, useState } from "react";
import { BellRing, Check, ExternalLink, LoaderCircle, Pencil, Plus, RefreshCw, RotateCcw, Send, Trash2, Webhook, X } from "lucide-react";
import type { NotificationChannel, NotificationDelivery, NotificationDeliveryStatus, NotificationEventType, Severity } from "../types/app.js";
import { api } from "../services/api.js";

const events: NotificationEventType[] = ["alert.created","alert.resolved","incident.created","incident.resolved"];
const severities: Severity[] = ["INFO","WARNING","CRITICAL"];
const statuses: Array<NotificationDeliveryStatus|"all"> = ["all","pending","delivering","delivered","failed"];

export const Notifications: React.FC = () => {
  const [channels,setChannels]=useState<NotificationChannel[]>([]);
  const [deliveries,setDeliveries]=useState<NotificationDelivery[]>([]);
  const [loading,setLoading]=useState(true),[deliveryLoading,setDeliveryLoading]=useState(false);
  const [working,setWorking]=useState<string|null>(null),[editingId,setEditingId]=useState<string|null>(null);
  const [error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
  const [channelFilter,setChannelFilter]=useState("all"),[statusFilter,setStatusFilter]=useState<NotificationDeliveryStatus|"all">("all");
  const [form,setForm]=useState<{name:string;url:string;event_types:NotificationEventType[];min_severity:Severity;enabled:boolean}>({name:"Production alerts",url:"",event_types:[...events],min_severity:"WARNING",enabled:true});

  async function loadChannels(){try{setLoading(true);setError(null);setChannels(await api.getNotificationChannels());}catch(e){setError(e instanceof Error?e.message:"Unable to load notification channels.");}finally{setLoading(false);}}
  async function loadDeliveries(){try{setDeliveryLoading(true);const rows=await api.getNotificationDeliveries({channelId:channelFilter==="all"?undefined:channelFilter,status:statusFilter==="all"?undefined:statusFilter,limit:200});setDeliveries(rows);}catch(e){setError(e instanceof Error?e.message:"Unable to load delivery history.");}finally{setDeliveryLoading(false);}}
  useEffect(()=>{void loadChannels();},[]);
  useEffect(()=>{void loadDeliveries();const t=window.setInterval(()=>void loadDeliveries(),10000);return()=>window.clearInterval(t);},[channelFilter,statusFilter]);
  function reset(){setEditingId(null);setForm({name:"Production alerts",url:"",event_types:[...events],min_severity:"WARNING",enabled:true});}
  function edit(c:NotificationChannel){setEditingId(c.id);setForm({name:c.name,url:c.url,event_types:[...c.event_types],min_severity:c.min_severity,enabled:c.enabled});}
  function toggleEvent(event:NotificationEventType){setForm(f=>({...f,event_types:f.event_types.includes(event)?f.event_types.filter(v=>v!==event):[...f.event_types,event]}));}
  async function save(){if(!form.name.trim()||!form.url.trim()||!form.event_types.length){setError("Name, webhook URL, and at least one event type are required.");return;}setWorking(editingId?editingId+":save":"create");setError(null);setNotice(null);try{if(editingId){const updated=await api.updateNotificationChannel(editingId,form);setChannels(rows=>rows.map(r=>r.id===editingId?updated:r));setNotice("Notification channel updated.");}else{const created=await api.createNotificationChannel(form);setChannels(rows=>[...rows,created].sort((a,b)=>a.name.localeCompare(b.name)));setNotice("Notification channel created.");}reset();}catch(e){setError(e instanceof Error?e.message:"Unable to save notification channel.");}finally{setWorking(null);}}
  async function toggle(c:NotificationChannel){setWorking(c.id);try{const u=await api.updateNotificationChannel(c.id,{enabled:!c.enabled});setChannels(rows=>rows.map(r=>r.id===c.id?u:r));setNotice(u.enabled?"Channel enabled.":"Channel paused.");setError(null);}catch(e){setError(e instanceof Error?e.message:"Unable to update channel.");}finally{setWorking(null);}}
  async function test(c:NotificationChannel){setWorking(c.id+":test");try{const r=await api.testNotificationChannel(c.id);setNotice("Test delivery queued: "+r.delivery_id);setError(null);await loadDeliveries();}catch(e){setError(e instanceof Error?e.message:"Unable to queue test delivery.");}finally{setWorking(null);}}
  async function remove(c:NotificationChannel){if(!window.confirm('Delete notification channel "'+c.name+'"?'))return;setWorking(c.id+":delete");try{await api.deleteNotificationChannel(c.id);setChannels(rows=>rows.filter(r=>r.id!==c.id));setNotice("Notification channel deleted.");setError(null);}catch(e){setError(e instanceof Error?e.message:"Unable to delete channel.");}finally{setWorking(null);}}
  async function retry(d:NotificationDelivery){setWorking(d.id);try{await api.retryNotificationDelivery(d.id);setNotice("Delivery queued for retry.");setError(null);await loadDeliveries();}catch(e){setError(e instanceof Error?e.message:"Unable to retry delivery.");}finally{setWorking(null);}}
  const names=new Map(channels.map(c=>[c.id,c.name]));
  return <main className="mx-auto max-w-7xl space-y-6 p-5 sm:p-8">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Automation</div><h1 className="mt-2 text-3xl font-semibold text-white">Notifications</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Manage signed webhooks for alert/incident lifecycle events and replay durable delivery failures.</p></div><button onClick={()=>void loadChannels()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-white/8 px-4 py-2.5 text-sm text-slate-300"><RefreshCw className={"h-4 w-4 "+(loading?"animate-spin":"")}/>Refresh</button></div>
    {(error||notice)&&<div role="alert" className={"rounded-xl border px-4 py-3 text-sm "+(error?"border-rose-500/15 bg-rose-500/5 text-rose-300":"border-emerald-500/15 bg-emerald-500/5 text-emerald-300")}>{error||notice}</div>}
    <section className="rounded-2xl border border-white/7 bg-white/[0.02] p-5"><div className="flex items-center gap-2 text-sm font-medium text-white"><Plus className="h-4 w-4 text-cyan-300"/>{editingId?"Edit webhook channel":"Create webhook channel"}</div><p className="mt-1 text-xs text-slate-600">Backend validation enforces safe webhook targets and signs outbound requests.</p><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Production alerts" className="rounded-xl border border-white/8 bg-slate-950 px-4 py-3 text-sm text-white"/><input value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="https://ops.example.com/webhook" className="rounded-xl border border-white/8 bg-slate-950 px-4 py-3 text-sm text-white xl:col-span-2"/><select value={form.min_severity} onChange={e=>setForm({...form,min_severity:e.target.value as Severity})} className="rounded-xl border border-white/8 bg-slate-950 px-3 py-3 text-sm text-white">{severities.map(s=><option key={s}>{s}</option>)}</select></div><div className="mt-4 flex flex-wrap gap-2">{events.map(e=><button type="button" key={e} onClick={()=>toggleEvent(e)} className={"rounded-full border px-3 py-1.5 text-xs "+(form.event_types.includes(e)?"border-cyan-300/20 bg-cyan-300/10 text-cyan-200":"border-white/8 text-slate-500")}>{form.event_types.includes(e)?"✓ ":""}{e}</button>)}</div><div className="mt-4 flex justify-between gap-3"><label className="flex items-center gap-2 text-xs text-slate-500"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>Enabled</label><div className="flex gap-2">{editingId&&<button onClick={reset} className="inline-flex items-center gap-1.5 rounded-xl border border-white/8 px-4 py-2.5 text-xs text-slate-400"><X className="h-3.5 w-3.5"/>Cancel</button>}<button onClick={()=>void save()} disabled={Boolean(working)||!form.event_types.length} className="inline-flex items-center gap-1.5 rounded-xl bg-cyan-300 px-4 py-2.5 text-xs font-semibold text-slate-950">{working==="create"||working?.endsWith(":save")?<LoaderCircle className="h-3.5 w-3.5 animate-spin"/>:<Check className="h-3.5 w-3.5"/>}{editingId?"Save changes":"Create channel"}</button></div></div></section>
    <section className="overflow-hidden rounded-2xl border border-white/7 bg-slate-900/50"><div className="border-b border-white/6 px-5 py-4 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Channels</div>{loading?<div className="p-8 text-sm text-slate-500">Loading channels…</div>:channels.length===0?<div className="p-10 text-center text-sm text-slate-500">No notification channels configured.</div>:<div className="divide-y divide-white/6">{channels.map(c=><div key={c.id} className="px-5 py-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Webhook className="h-4 w-4 text-cyan-300"/><span className="text-sm font-medium text-white">{c.name}</span><span className={"rounded-full border px-2 py-1 text-[10px] "+(c.enabled?"border-emerald-500/15 text-emerald-300":"border-white/8 text-slate-600")}>{c.enabled?"Enabled":"Paused"}</span><span className="rounded-full border border-white/8 px-2 py-1 text-[10px] text-slate-500">min {c.min_severity}</span></div><div className="mt-2 flex items-center gap-2 break-all text-xs text-slate-600"><ExternalLink className="h-3.5 w-3.5 shrink-0"/>{c.url}</div><div className="mt-2 flex flex-wrap gap-1.5">{c.event_types.map(e=><span key={e} className="rounded-full border border-white/7 px-2 py-1 text-[10px] text-slate-500">{e}</span>)}</div></div><div className="flex flex-wrap gap-2"><button onClick={()=>edit(c)} className="inline-flex items-center gap-1.5 rounded-xl border border-white/8 px-3 py-2 text-xs text-slate-400"><Pencil className="h-3.5 w-3.5"/>Edit</button><button onClick={()=>void toggle(c)} disabled={Boolean(working)} className="rounded-xl border border-white/8 px-3 py-2 text-xs text-slate-400">{c.enabled?"Pause":"Enable"}</button><button onClick={()=>void test(c)} disabled={!c.enabled||Boolean(working)} className="inline-flex items-center gap-1.5 rounded-xl border border-cyan-300/15 px-3 py-2 text-xs text-cyan-200"><Send className="h-3.5 w-3.5"/>{working===c.id+":test"?"Queueing…":"Send test"}</button><button onClick={()=>void remove(c)} disabled={Boolean(working)} className="inline-flex items-center gap-1.5 rounded-xl border border-rose-500/15 px-3 py-2 text-xs text-rose-300"><Trash2 className="h-3.5 w-3.5"/>Delete</button></div></div></div>)}</div>}</section>
    <section className="overflow-hidden rounded-2xl border border-white/7 bg-slate-900/50"><div className="border-b border-white/6 px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-sm font-semibold text-white">Delivery history</div><div className="mt-1 text-xs text-slate-600">Durable outcomes from the backend dispatcher.</div></div><div className="flex flex-wrap gap-2"><select value={channelFilter} onChange={e=>setChannelFilter(e.target.value)} className="rounded-xl border border-white/8 bg-slate-950 px-3 py-2 text-xs text-white"><option value="all">All channels</option>{channels.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value as typeof statusFilter)} className="rounded-xl border border-white/8 bg-slate-950 px-3 py-2 text-xs text-white">{statuses.map(s=><option key={s} value={s}>{s==="all"?"All statuses":s}</option>)}</select><button onClick={()=>void loadDeliveries()} disabled={deliveryLoading} className="rounded-xl border border-white/8 px-3 py-2 text-xs text-slate-400"><RefreshCw className={"h-3.5 w-3.5 "+(deliveryLoading?"animate-spin":"")}/></button></div></div></div>{deliveries.length===0?<div className="p-10 text-center text-sm text-slate-500">{deliveryLoading?"Loading deliveries…":"No deliveries match the current filters."}</div>:<div className="divide-y divide-white/6">{deliveries.map(d=><div key={d.id} className="px-5 py-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2 text-sm text-white"><BellRing className="h-4 w-4 text-cyan-300"/>{d.event_type}<span className={"rounded-full border px-2 py-1 text-[10px] "+(d.status==="delivered"?"border-emerald-500/15 text-emerald-300":d.status==="failed"?"border-rose-500/15 text-rose-300":"border-amber-500/15 text-amber-300")}>{d.status}</span><span className="text-xs text-slate-600">{names.get(d.channel_id)??d.channel_id}</span></div><div className="mt-1 text-xs text-slate-600">{new Date(d.created_at).toLocaleString()} · attempts {d.attempts}{d.last_status_code?" · HTTP "+d.last_status_code:""}{d.last_error?" · "+d.last_error:""}</div></div>{d.status==="failed"&&<button onClick={()=>void retry(d)} disabled={Boolean(working)} className="inline-flex items-center gap-1.5 rounded-xl border border-amber-400/15 px-3 py-2 text-xs text-amber-200"><RotateCcw className="h-3.5 w-3.5"/>Retry</button>}</div></div>)}</div>}</section>
  </main>;
};
export default Notifications;
