import React from "react";
import { ExternalLink, KeyRound, Radio, ShieldCheck } from "lucide-react";
import type { AuthUser } from "../types/app.js";

export const Settings: React.FC<{ user: AuthUser }> = ({ user }) => <main className="mx-auto max-w-5xl space-y-6 p-5 sm:p-8"><div><div className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Workspace</div><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">Settings</h1><p className="mt-2 text-sm text-slate-500">Review your access context and local workspace configuration.</p></div>
  <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-white/7 bg-white/[0.02] p-6"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-400/5"><ShieldCheck className="h-4 w-4 text-cyan-300"/></div><div><div className="text-sm font-semibold text-white">Account</div><div className="text-xs text-slate-600">Authenticated workspace identity</div></div></div><div className="mt-6 space-y-4"><div><div className="text-xs text-slate-600">Email</div><div className="mt-1 text-sm text-slate-200">{user.email}</div></div><div><div className="text-xs text-slate-600">Role</div><div className="mt-1 text-sm text-slate-200">{user.role}</div></div><div><div className="text-xs text-slate-600">Status</div><div className="mt-1 text-sm text-emerald-300">{user.is_active ? "Active" : "Inactive"}</div></div></div></div>
  <div className="rounded-2xl border border-white/7 bg-white/[0.02] p-6"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-400/5"><KeyRound className="h-4 w-4 text-indigo-300"/></div><div><div className="text-sm font-semibold text-white">Service connection</div><div className="text-xs text-slate-600">Current frontend/backend integration</div></div></div><div className="mt-6 space-y-4"><div><div className="text-xs text-slate-600">API endpoint</div><div className="mt-1 break-all text-sm text-slate-300">{import.meta.env.VITE_API_BASE_URL || "http://localhost:8000"}</div></div><div><div className="text-xs text-slate-600">Live stream</div><div className="mt-1 flex items-center gap-2 text-sm text-slate-300"><Radio className="h-4 w-4 text-cyan-300"/>Authenticated WebSocket telemetry</div></div><a href={(import.meta.env.VITE_API_BASE_URL || "http://localhost:8000") + "/docs"} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm text-cyan-300 hover:text-cyan-200">Open API documentation <ExternalLink className="h-4 w-4"/></a></div></div></div>
</main>;
export default Settings;
