import React, { useEffect, useState } from "react";
import { CheckCircle2, Clock3, LoaderCircle, Pencil, Play, Plus, RefreshCw, Trash2, X, XCircle } from "lucide-react";
import type { AuthUser, Service, SyntheticCheck, SyntheticCheckRun } from "../types/app.js";
import { api } from "../services/api.js";

export const SyntheticChecks: React.FC<{ user: AuthUser }> = ({ user }) => {
  const canEdit=user.role==="admin", canRun=user.role==="admin"||user.role==="operator";
  const [checks,setChecks]=useState<SyntheticCheck[]>([]),[services,setServices]=useState<Service[]>([]);
  const [selectedId,setSelectedId]=useState<string|null>(null),[runs,setRuns]=useState<SyntheticCheckRun[]>([]);
  const [loading,setLoading]=useState(true),[runsLoading,setRunsLoading]=useState(false),[working,setWorking]=useState<string|null>(null);
  const [editingId,setEditingId]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
  const [form,setForm]=useState({name:"API health",url:"https://example.com/health",service_id:"",method:"GET" as "GET"|"HEAD",interval_seconds:"30",timeout_seconds:"10",expected_status:"200",enabled:true});
  async function load(){try{setLoading(true);setError(null);const [c,s]=await Promise.all([api.getSyntheticChecks(),api.getServices()]);setChecks(c);setServices(s);setSelectedId(cur=>cur&&c.some(x=>x.id===cur)?cur:c[0]?.id??null);}catch(e){setError(e instanceof Error?e.message:"Unable to load synthetic checks.");}finally{setLoading(false);}}
  async function loadRuns(id:string){try{setRunsLoading(true);setRuns((await api.getSyntheticCheckRuns(id,100)).runs);}catch(e){setError(e instanceof Error?e.message:"Unable to load run history.");}finally{setRunsLoading(false);}}
  useEffect(()=>{void load();},[]);
  useEffect(()=>{if(selectedId)void loadRuns(selectedId);else setRuns([]);},[selectedId]);
  function reset(){setEditingId(null);setForm({name:"API health",url:"https://example.com/health",service_id:"",method:"GET",interval_seconds:"30",timeout_seconds:"10",expected_status:"200",enabled:true});}
  function edit(c:SyntheticCheck){setEditingId(c.id);setForm({name:c.name,url:c.url,service_id:c.service_id??"",method:c.method,interval_seconds:String(c.interval_seconds),timeout_seconds:String(c.timeout_seconds),expected_status:String(c.expected_status),enabled:c.enabled});}
  async function save(){const interval=Number(form.interval_seconds),timeout=Number(form.timeout_seconds),expected=Number(form.expected_status);if(!form.name.trim()||!form.url.trim()||![interval,timeout,expected].every(Number.isFinite)){setError("Check fields must be valid.");return;}setWorking(editingId?editingId+":save":"create");setError(null);setNotice(null);try{const payload={name:form.name.trim(),url:form.url.trim(),service_id:form.service_id||null,method:form.method,interval_seconds:interval,timeout_seconds:timeout,expected_status:expected,enabled:form.enabled};if(editingId){const updated=await api.updateSyntheticCheck(editingId,payload);setChecks(rows=>rows.map(x=>x.id===editingId?updated:x));setNotice("Synthetic check updated.");}else{const created=await api.createSyntheticCheck(payload);setChecks(rows=>[...rows,created].sort((a,b)=>a.name.localeCompare(b.name)));setSelectedId(created.id);setNotice("Synthetic check created.");}reset();}catch(e){setError(e instanceof Error?e.message:"Unable to save synthetic check.");}finally{setWorking(null);}}
  async function toggle(c:SyntheticCheck){setWorking(c.id);try{const u=await api.updateSyntheticCheck(c.id,{enabled:!c.enabled});setChecks(rows=>rows.map(x=>x.id===c.id?u:x));setNotice(u.enabled?"Check enabled.":"Check paused.");setError(null);}catch(e){setError(e instanceof Error?e.message:"Unable to update synthetic check.");}finally{setWorking(null);}}
  async function run(c:SyntheticCheck){setWorking(c.id+":run");try{const r=await api.runSyntheticCheck(c.id);setRuns(rows=>[...rows,r].sort((a,b)=>Date.parse(a.checked_at)-Date.parse(b.checked_at)).slice(-100));setChecks(rows=>rows.map(x=>x.id===c.id?{...x,last_run:r}:x));setNotice(r.success?"Synthetic check passed.":"Synthetic check failed.");setError(null);}catch(e){setError(e instanceof Error?e.message:"Unable to run synthetic check.");}finally{setWorking(null);}}
  async function remove(c:SyntheticCheck){if(!window.confirm('Delete synthetic check "'+c.name+'"?'))return;setWorking(c.id+":delete");try{await api.deleteSyntheticCheck(c.id);setChecks(rows=>rows.filter(x=>x.id!==c.id));if(selectedId===c.id){setSelectedId(null);setRuns([]);}setNotice("Synthetic check deleted.");setError(null);}catch(e){setError(e instanceof Error?e.message:"Unable to delete synthetic check.");}finally{setWorking(null);}}
  const selected=checks.find(c=>c.id===selectedId)??null, serviceName=(id:string|null)=>services.find(s=>s.id===id)?.name??"Unassigned";
  return <main className="mx-auto max-w-7xl space-y-6 p-5 sm:p-8"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Synthetic monitoring</div><h1 className="mt-2 text-3xl font-semibold text-white">Synthetic checks</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Verify HTTP availability and status behavior, optionally bind checks to services, and inspect durable run history.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-white/8 px-4 py-2.5 text-sm text-slate-300"><RefreshCw className={"h-4 w-4 "+(loading?"animate-spin":"")}/>Refresh</button></div>
  {(error||notice)&&<div role="alert" className={"rounded-xl border px-4 py-3 text-sm "+(error?"border-rose-500/15 bg-rose-500/5 text-rose-300":"border-emerald-500/15 bg-emerald-500/5 text-emerald-300")}>{error||notice}</div>}
  {canEdit&&<section className="rounded-2xl border border-white/7 bg-white/[0.02] p-5"><div className="flex items-center gap-2 text-sm font-medium text-white"><Plus className="h-4 w-4 text-cyan-300"/>{editingId?"Edit synthetic check":"Create synthetic check"}</div><p className="mt-1 text-xs text-slate-600">The backend validates target safety before a check is scheduled or executed.</p><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="API health" className="rounded-xl border border-white/8 bg-slate-950 px-4 py-3 text-sm text-white"/><input value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="https://example.com/health" className="rounded-xl border border-white/8 bg-slate-950 px-4 py-3 text-sm text-white xl:col-span-2"/><select value={form.service_id} onChange={e=>setForm({...form,service_id:e.target.value})} className="rounded-xl border border-white/8 bg-slate-950 px-4 py-3 text-sm text-white"><option value="">No service</option>{services.map(s=><option key={s.id} value={s.id}>{s.name} · {s.environment}</option>)}</select><select value={form.method} onChange={e=>setForm({...form,method:e.target.value as "GET"|"HEAD"})} className="rounded-xl border border-white/8 bg-slate-950 px-3 py-3 text-sm text-white"><option>GET</option><option>HEAD</option></select><input type="number" min="10" max="3600" value={form.interval_seconds} onChange={e=>setForm({...form,interval_seconds:e.target.value})} className="rounded-xl border border-white/8 bg-slate-950 px-3 py-3 text-sm text-white"/><input type="number" min="1" max="60" step="0.1" value={form.timeout_seconds} onChange={e=>setForm({...form,timeout_seconds:e.target.value})} className="rounded-xl border border-white/8 bg-slate-950 px-3 py-3 text-sm text-white"/><input type="number" min="100" max="599" value={form.expected_status} onChange={e=>setForm({...form,expected_status:e.target.value})} className="rounded-xl border border-white/8 bg-slate-950 px-3 py-3 text-sm text-white"/></div><div className="mt-4 flex items-center justify-between"><label className="flex items-center gap-2 text-xs text-slate-500"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>Enabled</label><div className="flex gap-2">{editingId&&<button onClick={reset} className="inline-flex items-center gap-1.5 rounded-xl border border-white/8 px-4 py-2.5 text-xs text-slate-400"><X className="h-3.5 w-3.5"/>Cancel</button>}<button onClick={()=>void save()} disabled={Boolean(working)} className="rounded-xl bg-cyan-300 px-5 py-2.5 text-xs font-semibold text-slate-950">{editingId?"Save changes":"Create check"}</button></div></div></section>}
  <div className="grid gap-6 xl:grid-cols-[1fr_0.9fr]"><section className="overflow-hidden rounded-2xl border border-white/7 bg-slate-900/50"><div className="border-b border-white/6 px-5 py-4 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Checks</div>{loading?<div className="p-8 text-sm text-slate-500">Loading checks…</div>:checks.length===0?<div className="p-10 text-center text-sm text-slate-500">No synthetic checks configured.</div>:<div className="divide-y divide-white/6">{checks.map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)} className={"block w-full px-5 py-5 text-left hover:bg-white/[0.025] "+(selectedId===c.id?"bg-cyan-400/[0.035]":"")}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-medium text-white">{c.name}</span><span className={"rounded-full border px-2 py-1 text-[10px] "+(c.enabled?"border-emerald-500/15 text-emerald-300":"border-white/8 text-slate-600")}>{c.enabled?"Enabled":"Paused"}</span><span className="text-[10px] text-slate-600">{serviceName(c.service_id)}</span></div><div className="mt-2 break-all text-xs text-slate-600">{c.method} {c.url}</div><div className="mt-2 text-[11px] text-slate-700">every {c.interval_seconds}s · timeout {c.timeout_seconds}s · expect {c.expected_status}</div></div>{c.last_run&&<span className={"rounded-full border px-2 py-1 text-[10px] "+(c.last_run.success?"border-emerald-500/15 text-emerald-300":"border-rose-500/15 text-rose-300")}>{c.last_run.success?"Healthy":"Failed"}</span>}</div></button>)}</div>}</section>
  <section className="rounded-2xl border border-white/7 bg-slate-900/50 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-sm font-semibold text-white">Run history</div><div className="mt-1 text-xs text-slate-600">{selected?.name??"Select a check"}</div></div>{selected&&<div className="flex gap-2">{canEdit&&<button onClick={()=>edit(selected)} className="inline-flex items-center gap-1.5 rounded-xl border border-white/8 px-3 py-2 text-xs text-slate-400"><Pencil className="h-3.5 w-3.5"/>Edit</button>}{canRun&&<button onClick={()=>void run(selected)} disabled={Boolean(working)} className="inline-flex items-center gap-1.5 rounded-xl bg-cyan-300 px-3 py-2 text-xs font-semibold text-slate-950"><Play className="h-3.5 w-3.5"/>{working===selected.id+":run"?"Running…":"Run now"}</button>}</div>}</div>{!selected?<div className="flex min-h-72 items-center justify-center text-sm text-slate-600">Select a check to inspect its history.</div>:runsLoading?<div className="flex min-h-72 items-center justify-center gap-2 text-sm text-slate-600"><LoaderCircle className="h-4 w-4 animate-spin"/>Loading run history…</div>:runs.length===0?<div className="mt-6 rounded-xl border border-white/7 bg-white/[0.02] p-8 text-center text-sm text-slate-500">No runs recorded yet.</div>:<div className="mt-5 space-y-2">{runs.slice().reverse().map(r=><div key={r.id} className="rounded-xl border border-white/7 bg-white/[0.02] p-4"><div className="flex items-center justify-between gap-3"><span className={"inline-flex items-center gap-2 text-xs "+(r.success?"text-emerald-300":"text-rose-300")}>{r.success?<CheckCircle2 className="h-4 w-4"/>:<XCircle className="h-4 w-4"/>}{r.success?"Passed":"Failed"}</span><span className="text-[11px] text-slate-600">{new Date(r.checked_at).toLocaleString()}</span></div><div className="mt-2 grid grid-cols-2 gap-2 text-xs text-slate-500"><span>HTTP {r.status_code??"—"}</span><span>{r.duration_ms.toFixed(1)} ms</span><span>Consecutive failures {r.consecutive_failures}</span><span>{r.error??"No error"}</span></div></div>)}</div>}</section></div>
  {!canEdit&&<div className="rounded-xl border border-white/8 bg-white/[0.02] px-4 py-3 text-xs text-slate-600"><Clock3 className="mr-2 inline h-3.5 w-3.5"/>Administrators manage definitions; operators can execute checks and inspect history.</div>}
  </main>;
};
export default SyntheticChecks;
